### ISSUE TITLE
Include more flexmark extensions for improved markdown to html rendering

### ISSUE THREAD

**Issue by UBessle** [avisi-cloud/structurizr-site-generatr#121]
we would like to move our architecture documentation from Confluence pages to structurizr models, and markdown files using your excellent tool structurizr-site-generatr.

Unfortunately currently we miss some possibilities to achieve this goal in a satisfactory way. The main drawback is, that confluence provides much more formatting possibilities, than the basic markdown support from flexmark inside of structurizr-site-generatr.

We've looked into flexmark and it looks, as nearly everything would be possible with flexmark as well, if we could use some of the numerous existing flexmark extensions. But currently structurizr-site-generatr is restricted to be using tables extension only.

```
// MarkdownToHtml.kt
options.set(Parser.EXTENSIONS, listOf(TablesExtension.create()))
```

It would be great, if we could use at least the following extension additionally
* [AnchorLink](https://github.com/vsch/flexmark-java/wiki/Extensions#anchorlink)
* [Emoji](https://github.com/vsch/flexmark-java/wiki/Extensions#emoji)
* [Gfm-TaskList](https://github.com/vsch/flexmark-java/wiki/Extensions#gfm-tasklist)
* [GitLab Flavoured Markdown](https://github.com/vsch/flexmark-java/wiki/Extensions#gitlab-flavoured-markdown)
* [Table-of-Contents-Extension](https://github.com/vsch/flexmark-java/wiki/Table-of-Contents-Extension)

It would be even better, if we could somehow control, which extensions are used and which options are set. Than we could later on decide, to use additional extensions as well, like
* admonition
* Autolink
* Gfm-Users
* Footnotes
* ...

**Comment by dirkgroot** [comment]
@UBessle thanks for the issue! Looking at the functionalities of the available Flexmark plugins, I really like this idea!

We'll have to think about how to make adding and configuring Flexmark plugins dynamic, as opposed to hardcoded. Ideally, I would like this to be configurable using a `properties` block in the Structurizr DSL model at `workspace` level. Something like:

```
workspace {
  properties {
    "flexmark.plugins" "AnchorLink,Emoji"
    "flexmark.Emoji.USE_IMAGE_TYPE" "UNICODE_ONLY"
  }
}
```

I'm not sure how hard or easy it would be to implement this. Any ideas?

**Comment by dirkgroot** [comment]
Maybe you're right. The reason for my idea of using workspace-level properties is that Simon Brown also uses properties on the workspace, views and model elements to customize the generation of diagrams. See https://github.com/structurizr/export/tree/main/src/main/java/com/structurizr/export/plantuml.

However, I'm not sure if I like that approach. I think that a separate configuration file may indeed be a better approach, also because I think that JSON or YAML may be better suitable for this kind of configuration.

**Comment by UBessle** [comment]
May we help you somehow in producing this improvement?

**Comment by UBessle** [comment]
I'm not an experienced Kotlin developer. Could you please provide a small section in the README.md how to participate in development?
- how to build locally
- how to run tests locally
- how to run locally built versions
- how to document changes / provide updated documentation
This would help me (and perhaps others as well) to come up to speed in short time

**Comment by simonbrowndotje** [comment]
> The reason for my idea of using workspace-level properties is that Simon Brown also uses properties on the workspace, views and model elements to customize the generation of diagrams. ... However, I'm not sure if I like that approach.

Yup, I've learnt (the hard way) that many people using the Structurizr toolset are "architects" rather than developers, some with a very limited technical background. It's for this reason I tend to err on the side of opinionated simplicity. 😂

**Comment by dirkgroot** [comment]
But architects ARE developers... right...? 😉

But I understand your choice. Architects come in many shapes and forms and have very different backgrounds. Creating something like this for such a diverse group of users is hard.

For this tool, I think we should lean towards sensible defaults resulting in something that's usable for lots of people "out of the box", and some optional configurability for "advanced" users.

**Comment by dirkgroot** [comment]
@UBessle That's a good idea. I'm a bit busy lately, but I'll try to add a `CONTRIBUTING.md` somewhere in the upcoming week.

**Comment by dirkgroot** [comment]
@UBessle I've added [`CONTRIBUTING.md`](https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/CONTRIBUTING.md), with some basic information on working with the source code. Is this sufficient for you to get started?

**Comment by UBessle** [comment]
Thanks for the CONTRIBUTING description. I was absent last week. Hopefully i can start working on the PR next week.

**Comment by jp7677** [comment]
I've finally took some time to document the `structurzr` properties that affect the look and feel of the generated web site, see https://github.com/avisi-cloud/structurizr-site-generatr/pull/206. In my opinion, any configuration switches we add for markdown rendering would be in the same league as those and thus should be properties in the `view` section of the C4 DSL (applied it looks like https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/docs/example/workspace.dsl#L159).

**Comment by simonbrowndotje** [comment]
Just my 2c ... I can see properties named `structurizr.style.*` confusing people. Why not name them something like `generatr.style.*` to make it explicit these are Site Generatr specific properties?

**Comment by jp7677** [comment]
> Just my 2c ... I can see properties named `structurizr.style.*` confusing people. Why not name them something like `generatr.style.*` to make it explicit these are Site Generatr specific properties?

Yeah, I agree. `site-generatr.style.*`, `site-generatr.search.*` (and may be `site-generatr.markdown.*` in the future) might even be better.
Well, naming is hard :)

**Comment by dirkgroot** [comment]
Thanks for your feedback, @simonbrowndotje! I completely agree that using the `stucturizr` prefix could lead to confusion.

**Comment by dirkgroot** [comment]
I'm closing this issue, as the requested feature is now built and merged to `main`.
