### ISSUE TITLE
development server battles git

### ISSUE THREAD

**Issue by YoeriVD** [avisi-cloud/structurizr-site-generatr#162]
Using the `serve` command is extremely useful, especially thanks to the hot reload. ❤️
However, in my case it seems to be a bit "eager"

`Detected a change in ***/.git/logs/refs/heads/yvd, updating site...`

I think it might be a good idea to ignore the .git folder.

**Comment by jp7677** [comment]
We don't have our models in a repository root level, since this never surfaced, so thanks for the hint ;). 
See linked PR.

**Comment by jp7677** [comment]
This should be fixed now starting with https://github.com/avisi-cloud/structurizr-site-generatr/commit/41ce22295a92d1c260a6c600249f8ca103af3af6 , feel free to reopen if the issue still occurs.
