### ISSUE TITLE
Container level diagrams are not linked to components

### ISSUE THREAD

**Issue by qtzar** [avisi-cloud/structurizr-site-generatr#164]
When looking at the container level digram the components within that container are not linked to the relevant component view if it exists. It would be nice if I could click on a component and have it move to that diagram automatically.

**Comment by jp7677** [comment]
Yeah, this is a good idea. Lets wait first how https://github.com/avisi-cloud/structurizr-site-generatr/pull/149 / https://github.com/avisi-cloud/structurizr-site-generatr/pull/149#issuecomment-1451393506 turns out for the tab support which is imho also useful here.
