### ISSUE TITLE
asset folder not being copied

### ISSUE THREAD

**Issue by macasas** [avisi-cloud/structurizr-site-generatr#174]
Hi, have just installed latest version, starting from scratch.  Running serve or generate, as per your github readme examples, the resulting folders do not contain the asset folder, nor does localhost:8080 show the images, just empty image tags.

Is there a switch I am not using correctly?

Thanks
Dave

**Comment by jp7677** [comment]
There is indeed a `-a` /`--assetsDir` switch, did you used that?

The arguments for serving the example site would e.g. look like:
```
serve --workspace-file docs/example/workspace.dsl --assets-dir docs/example/assets
```

**Comment by macasas** [comment]
Happy days, thanks for quick response.  This is a great setup for docs + diagram site building.  Thanks.
