### ISSUE TITLE
Multiple dependencies on other software system

### ISSUE THREAD

**Issue by bluecitylights** [avisi-cloud/structurizr-site-generatr#208]
When we have multiple dependencies on another system, the diagrams just show one of them. Probably will be too much clutter to show all of them on the connecting lines.
But in the dependencies table, we also only see one of the descriptions. This could be solved by showing multiple rows in the table maybe.

**Comment by dirkgroot** [comment]
I @bluecitylights, thanks for your issue. Could you please add an example model which demonstrates the situation you're describing?

**Comment by bluecitylights** [comment]
@dirkgroot 
I think this dependencies table is generated by site-generator.
We probably can display multiple relations from syste1 to system2 by adding multiple rows.

```
workspace {
    !docs doc
    !adrs adr
    
    !identifiers hierarchical
    
    model {
        system1 = softwareSystem "System1" {
            cont = container "container 1.1"{
            }
        }
    
        system2 = softwareSystem "System2"{
            cont21 = container "container 2.1"
            cont22 = container "container 2.2"

        }
        
        system1.cont -> system2.cont21 "rel1"
        system1.cont -> system2.cont22 "rel2"

        

    }
    
    views {
        systemLandscape  "SystemLandscape" {
            include *
            autolayout
        }
        
        systemContext system1 "system1" {
            include *
            autolayout
        }

 
    }

}
```

![image](https://user-images.githubusercontent.com/30653230/233439215-6e63b3fc-c410-4559-bca5-4a91c04e3787.png)

**Comment by qtzar** [comment]
While the dependencies table is generated by site-generatr it can only use the information that is in the model after it has been parsed by the Structurizr DSL. The dependencies table also only shows system to system relationships.

By default the Structurizr DSL will create implied relationships where none already exist and then add them to the model. In your sample dsl  your are doing container to container relationships and the DSL parser is adding in a system to system relationship but it will only add one of them ( based on the first one it encounters in the file ). This is why you only see a single line in the dependencies table.

You could add the following to the top of your DSL file which will change the strategy used for building the implied relationships. But also causes those lines to show on the diagrams as well as in the table which can lead to very cluttered diagrams.

!script groovy {
      workspace.model.impliedRelationshipsStrategy = new com.structurizr.model.CreateImpliedRelationshipsUnlessSameRelationshipExistsStrategy()
    }

**Comment by bluecitylights** [comment]
This works indeed, thanks.

**Comment by dirkgroot** [comment]
Thanks @qtzar for helping out!

> This works indeed, thanks.

Cool! I'm closing this issue then.
