### ISSUE TITLE
Invalid PlantUML generated since 1.1.0

### ISSUE THREAD

**Issue by drazzib** [avisi-cloud/structurizr-site-generatr#221]
Since latest structurizr-site-generatr 1.1.0 release I'm getting some "`Syntax Error?`" from PlantUML SVG renderer.

I've found that, under certain conditions, generated `puml` file contains an empty link (which seems invalid) :

`Container(system.SystemBFF, "System BFF", "NodeJS", "Back-For-Frontend", $tags="Container,API,NodeJS")[[]]`

AFAIK, this issue seems to have been introducted by #183

**Comment by qtzar** [comment]
Do you have a sample DSL that can be used to duplicate this issue?

**Comment by drazzib** [comment]
Hi @qtzar !

Here is a sample DSL which I've build to reproduce this particular issue
```
workspace "Sample C4 Architecture" {

    !identifiers hierarchical

    model {
        s1 = softwareSystem "S1" {

            bff = container "S1 BFF" {
                tags "API"
                technology "NodeJS"

                dataset_route = component "Dataset route"
            }

            front = container "S1 Front" {
                tags "Frontend"
                technology "ReactJS"

                home = component "Home Page"

                listing = component "Listing dataset 1" {
                    -> s1.bff.dataset_route "" "HTTPS"
                }
            }
        }
    }

    views {
        properties {
            "c4plantuml.tags" "true"
        }

        component s1.front "S1front" {
            include *
            autoLayout
        }

        component s1.front "S1ListingComponents" {
            title "Components - focus on Abnormal Margin"
            include ->s1.front.listing->
            autoLayout
        }

    }
}
```

Running `structurizr-site-generatr serve --workspace-file workspace.dsl` will be "Successfully generated diagrams and site"

http://localhost:8080/master/s1/component/ will display in **embedded SVG** with previous error message

**Comment by drazzib** [comment]
Hi @qtzar !

I think I've found and corrected this issue in PR #222

Could you have a look ?

**Comment by jp7677** [comment]
@drazzib Merged, thanks a lot for your help with this issue!

**Comment by drazzib** [comment]
Hi @jp7677 !
I can confirm this issue is fixed on latest commit on main branch (tested on a project which was failing before) 👍🏻
