### ISSUE TITLE
Styles support?

### ISSUE THREAD

**Issue by pcolby** [avisi-cloud/structurizr-site-generatr#233]
Hi, thanks for an awesome tool! 😄 

Most styles do not seem to work for me, so before I dig a bit deeper, I thought I'd quickly ask if its expected to work.

For example, if I have:

```
      element "Database" {
        shape Cylinder
        color #ff0000
        background #dddd00
        stroke green
        opacity 50
      }
```

The `shape` (ie `Cylinder`) will take effect, but none of the other properties. And actually the `shape` only seems to take effect with some values, but not all of the official DSL shapes.  Is this just not supported (yet), or shall I dig deeper?

Thanks!

**Comment by jp7677** [comment]
Hi. you are welcome :)

Did you set 

```
"c4plantuml.tags" "true"
```

in your views properties?


That switch can make a difference. See also https://github.com/avisi-cloud/structurizr-site-generatr#customizing-the-generated-website and  https://github.com/structurizr/export/tree/main/src/main/java/com/structurizr/export/plantuml#c4plantumlexporter

**Comment by pcolby** [comment]
Ah, that was it! I hadn't realised that needed. My styles are all working now 😄 

Thanks again!

**Comment by brnhffmnn** [comment]
I keep forgetting to set this property. 😅
Couldn't this be applied by default?
