### ISSUE TITLE
Dynamic Diagrams are rendered, but not displayed

### ISSUE THREAD

**Issue by mariusburfey** [avisi-cloud/structurizr-site-generatr#234]
Hey everyone and thank you for building this awesome tool!
I am currently evaluating whether we want to use it in combination with Gitlab Pages for our engineers. It looks very promising!

But I am wondering, whether [Dynamic Diagrams](https://c4model.com/#DynamicDiagram) are supported: The diagrams are rendered (as puml, svg and png, everything seems fine), but I can't find them on the website. Are they displayed anywhere or does this feature not (yet) exist?

The [example](https://structurizr.com/dsl?example=big-bank-plc) contains such a diagram called "SignIn".

Thanks and best regards,
Marius

**Comment by jp7677** [comment]
There is currently indeed no dedicated page for showing dynamic diagrams. I don’t know/remember if there is a specific reason for that, I guess we just haven’t had the need for that.

What you can do however, is to embed those diagrams in a markdown document and add het markdown as documentation to your software system (see https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/docs/example/workspace-docs/01-embedding-diagrams-and-images.md as an example).

**Comment by mariusburfey** [comment]
Thanks! 
This works fine for me.

**Comment by jp7677** [comment]
Cool to hear. That said I think it would actually be a good idea to also show dynamic diagrams on a dedicated page like we do with deployment diagrams. 
Let’s keep this issue open as a reminder.

**Comment by jeremyjousse** [comment]
@jp7677 The main interest of dynamic diagrams is also to use them as a sequence diagram, and use the next/previews/play "dynamic" feature. A simple SVG is losing interest 😞 .
<img width="318" alt="image" src="https://github.com/avisi-cloud/structurizr-site-generatr/assets/1360208/8fd5049b-dac7-4592-b557-b3966950921d">
