### ISSUE TITLE
The `build/puml-cache` folder gets left in current working directory

### ISSUE THREAD

**Issue by pcolby** [avisi-cloud/structurizr-site-generatr#247]
Thanks a again for an excellent project! :)

One small thing, if I ask Structurizr Site Generatr to output to a folder somewhere else, it still ends up creating a `./build/puml-cache/` hierarchy in the current working directly, and leaving it there.

eg

```
$ ls
workspace.dsl
$ structurizr-site-generatr generate-site --output-dir /tmp/arch-site --workspace-file workspace.dsl
...
$ ls
build workspace.dsl
$ find build/
build/
build/puml-cache
$
```

This isn't a problem, just a bit messy.  Ideally the folder would get cleaned-up afterwards, or there'd be some way of specifying where to have it created, so it doesn't have to pollute my source tree :)

Thanks!

**Comment by dirkgroot** [comment]
Hi @pcolby, you're welcome 😃!

The `build` directory in the current working is intended to be added to your `.gitignore`, just like for example the `target` directory of a Maven project. Any "temporary" files in there are actually reused the next time you perform a `generate-site` or `serve`.

I think adding a `--build-dir` option, allowing one to specify where the `build` directory should be created would be a nice-to-have feature for people who want to keep their source directory clean.

**Comment by dirkgroot** [comment]
I'm closing this issue for now.
