### ISSUE TITLE
links between ADR's are not working in generated site

### ISSUE THREAD

**Issue by UBessle** [avisi-cloud/structurizr-site-generatr#260]
Structurizr-site-generatr supports ADR's as part of the architecture documentation for the workspace as well as for systems and even containers.

ADR support is already part of structurizr, where it's states, that the format proposed by [adr-tools](https://github.com/npryce/adr-tools) from Michael Nygard should be used for these ADR files (https://structurizr.com/help/decision-log).

Part of the formating rules for ADR files is the definition how ADR's may be linked to each other, because a later ADR could replace or amend an earlier one. You find an example in the adr-tools repository, where ADR [0005-help-comments.md](https://github.com/npryce/adr-tools/blob/master/doc/adr/0005-help-comments.md) is amended by [ADR 0009-help-scripts.md](https://github.com/npryce/adr-tools/blob/master/doc/adr/0009-help-scripts.md).

Unfortunately these links do not work in the generated site from structurizr-site-generatr. 

How to reproduce the problem
* [install adr-tools](https://github.com/npryce/adr-tools/blob/master/INSTALL.md) if they are not yet available
* cd to docs/example from structurizr-site-generatr
* `adr new Use MySQL Database`
  creates workspace-adrs/0002-use-mysql-database.md
* `adr new -s 2 Use PostgreSQL Database`
  creates workspace-adrs/0003-use-postgresql-database.md

Content of workspace-adrs/0003-use-postgresql-database.md will be
```
# 3. Use PostgreSQL Database

Date: 2023-07-06

## Status

Accepted

Supercedes [2. Use MySQL Database](0002-use-mysql-database.md)

## Context

The issue motivating this decision, and any context that influences or constrains the decision.

## Decision

The change that we're proposing or have agreed to implement.

## Consequences

What becomes easier or more difficult to do and any risks introduced by the change that will need to be mitigated.
```

* start development server `./gradlew run --args "serve -w docs/example/workspace.dsl"`
* open generated site and navigate to Decisions page (http://localhost:8080/master/decisions/)
* check working link to Decision 2 "Use MySQL Database":
  http://localhost:8080/master/decisions/2/
* open Decsision 3 (http://localhost:8080/master/decisions/3/)
* check link to "2. Use MySQL Database" in Status section of the decision page:
  http://localhost:8080/master/#2
* Try to click on the link to "2. Use MySQL Database". The broken link brings you back to the Home page of Big Bank plc architecture but not to the ADR page for "2. Use MySQL Database".

**Comment by MartinC-MCN** [comment]
Can confirm I have the same issue. Could not find a way around it without specifying explicitly the absolute URL, which would in turn break the actual link between the 2 markdowns outside of the context of the website

**Comment by dirkgroot** [comment]
@UBessle Thanks for reporting this issue. I've created #284 to fix this.
