### ISSUE TITLE
v1.1.3 Install via HomeBrew is not working

### ISSUE THREAD

**Issue by qtzar** [avisi-cloud/structurizr-site-generatr#261]
getting the following error when attempting to run locally ( serve -w workspace.dsl )

```
/usr/local/bin/structurizr-site-generatr: line 2: /usr/local/Cellar/structurizr-site-generatr/1.1.3/libexec/bin/structurizr-site-generatr: No such file or directory
/usr/local/bin/structurizr-site-generatr: line 2: exec: /usr/local/Cellar/structurizr-site-generatr/1.1.3/libexec/bin/structurizr-site-generatr: cannot execute: No such file or directory
```

**Comment by qtzar** [comment]
Looking at the Homebrew Tap the download file has changed path. I wonder if that might be the cause.

Currently `https://github.com/avisi-cloud/structurizr-site-generatr/archive/1.1.3.tar.gz`
Previously `https://github.com/avisi-cloud/structurizr-site-generatr/releases/download/1.1.2/structurizr-site-generatr-1.1.2.tar.gz`

**Comment by dirkgroot** [comment]
Thanks for reporting this! I'm keeping the Homebrew repo up to date using Renovate. Sometimes, however, Renovate messes up the download link in the formula. I'm going to fix this right away.

**Comment by dirkgroot** [comment]
The download link is fixed now. Thanks again for reporting!
