### ISSUE TITLE
asciidoc support

### ISSUE THREAD

**Issue by illnr** [avisi-cloud/structurizr-site-generatr#282]
Hi, thanks for your great work. We are using asciidoc for our documentation files. Asciidoc is supported by Structurizr. I would love to see asciidoc support! Maybe you could utilise https://docs.asciidoctor.org/asciidoctorj/latest/ ?

**Comment by dirkgroot** [comment]
Hi @illnr. Adding support for Asciidoc is surely possible. However, due to time constraints, I'm not sure if we'll be able to add this any time soon.

We welcome contributions, so if you're comfortable doing so, feel free to file a PR which adds this.

**Comment by illnr** [comment]
Hi @dirkgroot, I took the time to do that. Welcoming any feedback. Thank you 😊
