### ISSUE TITLE
Option to use locally hosted CDN dependencies

### ISSUE THREAD

**Issue by toorog** [avisi-cloud/structurizr-site-generatr#285]
Structurizr site-generatr currently loads dependencies from cdn.jsdelivr.net. This is a potential privacy issue, since it leaks at least the IP addresses to jsdelivr. Also structurizr-site-generatr cannot be used in environments without internet connection.

Can we introduce a configuration setting that allows loading these dependencies from a local directory instead?

**Comment by toorog** [comment]
I've resolved this in my fork by doing the following change for all CDN resources: `https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css` -> `${viewModel.cdnBaseUrl}/bulma@0.9.3/css/bulma.min.css`.

`cdnBaseUrl`resolves to the value of a view property where the user may define a custom jsdelivr mirror (local files in `/cdn` folder in my case). This would enable users to pick their own CDN as long as the directory structure remains the same.

Would a PR to contribute these changes be welcome?

**Comment by jp7677** [comment]
Sorry for the late response. Once https://github.com/avisi-cloud/structurizr-site-generatr/pull/328 is in, I would be open to a PR that allows overriding the CDN base url.
