### ISSUE TITLE
Fails to generate on git branches with a `/` in the name

### ISSUE THREAD

**Issue by pietermees** [avisi-cloud/structurizr-site-generatr#289]
For branches named like `x/y` this line only extracts the part after the `/`. Site generation subsequently fails, presumably because it's trying to process a branch that doesn't exist?
https://github.com/avisi-cloud/structurizr-site-generatr/blob/e0e6f3b10af3041db8346e10bb1d30c4a346c010/src/main/kotlin/nl/avisi/structurizr/site/generatr/ClonedRepository.kt#L55

**Comment by pietermees** [comment]
I assume the intent is to strip away the `origin/` prefix so maybe the intent is to use `substringAfter` rather than `substringAfterLast`?

**Comment by dirkgroot** [comment]
Hi @pietermees, thanks for raising this issue.

You're right. The intent is to strip away the name of the remote.
