### ISSUE TITLE
No diagrams generated

### ISSUE THREAD

**Issue by mlevin2** [avisi-cloud/structurizr-site-generatr#324]
I'm using the homebrew install. When I execute `structurizr-site-generatr serve -w workspace.dsl`, I get no errors, and the local site can be viewed, but I get no diagrams. I can see the text description of all of the systems and containers. Same issue if I run `structurizr-site-generatr generate-site -w workspace.dsl -o site` and browse the static files.

I must be overlooking something very simple. Any ideas?

**Comment by galuszkak** [comment]
Hey @mlevin2 ,

Do you have more details to debug this. Can you provide:
- What Operating System are you using?
- Can you provide a minimum reproducible `workspace.dsl` on which this is actually failing for You? 

This would help try to reproduce this issue and help you.

My gut feeling is that you defined the model in DSL but you didn't define any views, and that is why you don't see any diagrams. But it's just my guess on this.

**Comment by qtzar** [comment]
If the views block is missing then all the default views would be created by default.

My guess is that there is a views block, maybe defining a single landscape view, but no system or container views have been defined. Once a single view is defined the default views are disabled.

On my workspace I added the following script to the views block

```
!script groovy {
    workspace.views.createDefaultViews()
}
```

This creates all the default views again.

**Comment by mlevin2** [comment]
Thanks! I had an import disabled \*embarrassed\*

Adding the defaults as @qtzar suggested made me realize my error.
