### ISSUE TITLE
Diagrams in multi branch sites are showing wrong diagrams

### ISSUE THREAD

**Issue by qtzar** [avisi-cloud/structurizr-site-generatr#347]
When using the 'All Branches' or 'Named Branches' option to create a multi-branch site the diagrams on all branches but the main branch are showing the wrong diagram. ie. you click the context view for SystemC but it shows the diagram for SystemA on the screen.

Download links for the svg, png and puml files are referencing the correct diagram.

I suspect that this is something to do with #308

**Comment by jp7677** [comment]
Hi @qtzar 
Thanks for the issue, the multiple branch logic hits us fairly often with regressions, time to think for a better testing approach...
Anyway, looking into this, I also think this is a side effect of the commit you found.

Are you able to test this easily? The following patch should resolve this, but I'm not completely sure:

```diff
--- a/src/main/kotlin/nl/avisi/structurizr/site/generatr/site/DiagramGenerator.kt
+++ b/src/main/kotlin/nl/avisi/structurizr/site/generatr/site/DiagramGenerator.kt
@@ -38,10 +38,10 @@ fun generateDiagrams(workspace: Workspace, exportDir: File) {
 
 private val diagramCache = ConcurrentHashMap<String, String>()
 
-fun generateDiagramWithElementLinks(workspace: Workspace, view: View, url: String): String {
+fun generateDiagramWithElementLinks(workspace: Workspace, view: View, url: String, branch: String): String {
     val diagram = generatePlantUMLDiagramWithElementLinks(workspace, view, url)
 
-    val name = "${diagram.key}-${view.key}"
+    val name = "$branch-${diagram.key}-${view.key}"
     return diagramCache.getOrPut(name) {
         val reader = SourceStringReader(diagram.withCachedIncludes().definition)
         val stream = ByteArrayOutputStream()
diff --git a/src/main/kotlin/nl/avisi/structurizr/site/generatr/site/SiteGenerator.kt b/src/main/kotlin/nl/avisi/structurizr/site/generatr/site/SiteGenerator.kt
index 9dd41dc..0ae6375 100644
--- a/src/main/kotlin/nl/avisi/structurizr/site/generatr/site/SiteGenerator.kt
+++ b/src/main/kotlin/nl/avisi/structurizr/site/generatr/site/SiteGenerator.kt
@@ -63,7 +63,7 @@ fun generateSite(
 ) {
     val generatorContext = GeneratorContext(version, workspace, branches, currentBranch, serving) { key, url ->
         workspace.views.views.singleOrNull { view -> view.key == key }
-            ?.let { generateDiagramWithElementLinks(workspace, it, url) }
+            ?.let { generateDiagramWithElementLinks(workspace, it, url, currentBranch) }
     }
 
     val branchDir = File(exportDir, currentBranch)
```

**Comment by qtzar** [comment]
@jp7677 

The cache is most certainly the issue here and it has been exacerbated by a change in the structurizr core where diagram keys can be auto generated like SystemContext-001, SystemContext-002 making it much easier to have an overlap between branches.

I was able to test your patch by creating a repository with multiple branches that were very different from each other and using the serve command to build the multi-branch site. I verified the bad diagrams showing, applied the patch and verified that the correct diagrams were showing.

While this approach worked it also lead me to uncover another issue with the cache. When using the serve command the cache stays in memory after all the diagrams are generated. Then if you then edit a dsl file the diagrams are regenerated but they don't update on screen ( the downloadable versions are updated ). I suspect that the cache is kicking in and just bringing back the original generated diagram. This also happened on a non multi-branch run of the serve command and has already been spotted by one of our enginneers who was trying to update diagrams in our corporate diagram repository. Even with the patch above this was happening.

I think a better approach would be to either empty the cache between branches or remove it completely.

**Comment by qtzar** [comment]
I can confirm that this resolves the issue.

Here is the run command I'm using if you want to check it out yourself. I've made the test repository public, it is basically all the structurizr samples but with the default views enabled so there is a bigger chance of overlap between branches for cache hits.

Prior to fix you could see bad diagrams in the Big Bank branch on the ATM Context or Internet Banking Container pages.

```
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="Generate Multi-Branch Git Repository - qtzar/structurizr-test-workspace" type="JetRunConfigurationType">
    <option name="MAIN_CLASS_NAME" value="nl.avisi.structurizr.site.generatr.AppKt" />
    <module name="structurizr-site-generatr.main" />
    <option name="PROGRAM_PARAMETERS" value="generate-site --git-url https://github.com/qtzar/structurizr-test-workspace.git --workspace-file workspace.dsl --all-branches --default-branch main " />
    <shortenClasspath name="NONE" />
    <method v="2">
      <option name="Make" enabled="true" />
    </method>
  </configuration>
</component>
```

**Comment by jp7677** [comment]
Thanks a lot, I've created a PR and hopefully this time we are good (for real).

**Comment by qtzar** [comment]
In regards to testing in the future...

I was wondering if it would be possible to create 'Release Candidate' style releases, both on Github but also a docker image and Brew image but using a :next tag. If this could be done automatically when a PR is merged to the main branch I'd be willing to setup my workflows to start using that release and if I see regression issues they can be addressed before a stable release is done on the :latest tag.

**Comment by jp7677** [comment]
Yes, something like this is certainly a good idea. We will come back to this. 
Thanks for your thoughts (and of course also for your contributions over the last months)!
