### ISSUE TITLE
plantuml/structurizr exporter

### ISSUE THREAD

**Issue by mlevin2** [avisi-cloud/structurizr-site-generatr#367]
Hi,

Is there any way to tell structurizr-site-generatr to use the *plantuml/structurizr* exporter as in `structurizr-cli export -f plantuml/structurizr -o generated -w workspace.dsl`?

structurizr-site-generatr is awesome, but I would like to get the same visual style when using it that I get when exporting via cli.

I believe that uses https://github.com/structurizr/export/blob/main/src/main/java/com/structurizr/export/plantuml/StructurizrPlantUMLExporter.java.

**Comment by romanlum** [comment]
i created a PR to select the exporter and implemented the `structurizr` exporter :)
see https://github.com/avisi-cloud/structurizr-site-generatr/pull/382

**Comment by jp7677** [comment]
PR https://github.com/avisi-cloud/structurizr-site-generatr/pull/406 (based on @romanlum work) also addresses this. Feedback is very welcome.
