### ISSUE TITLE
search related: lunr js broken link and character lower limit

### ISSUE THREAD

**Issue by reedxiao** [avisi-cloud/structurizr-site-generatr#389]
Great work! However,  I encounter 2 issues. Would you please have a look at:

### Issue 1. 

When using the customization option `generatr.search.language` with setting like below

```
views {
       properties {
            "generatr.search.language" "ja"
        }
...
    }
```

The output embeded js is like 

```HTML
<h2>Search results</h2>

  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/lunr@2.3.9/lunr.min.js"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/lunr-languages@1.14.0@1.14.0/min/lunr.stemmer.support.min.js"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/lunr-languages@1.14.0/min/lunr.ja.min.js"></script>

```

I believe the `@1.14.0@1.14.0` part is a duplicated version number, which makes the link broken.
Can this be fixed?

### Issue 2. 

There is a lower limit (at least 3 chars) in the output site search field. Because characters in Asian language (instead of letters) can mean a lot and a word usually consist  of 1-3 chars,  it may be a good idea to allow customization  (limit to 2?) or allow removing the limit.

Thanks!

**Comment by jp7677** [comment]
Hi,

Thanks for the report. Are you able to test and create a PR? The offending line for 1 is here https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/src/main/kotlin/nl/avisi/structurizr/site/generatr/site/views/CDN.kt#L39  

Furthermore I'm absolutely fine to reduce the limit to just one character. I never thought about your use case. This means to adjust https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/src/main/kotlin/nl/avisi/structurizr/site/generatr/site/views/PageHeader.kt#L32 and here https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/src/main/resources/assets/js/header.js#L2

**Comment by reedxiao** [comment]
@jp7677  Sorry for the late response, I will test it and report the result here later. Thanks again!

**Comment by reedxiao** [comment]
@jp7677  `./gradlew test` all passed. The broken link fixed. Search char limit lifted. 

Everything is fine except that I found using Chinese need node env by default, or need to use 3rd party lunr-language version and there are pros and cons.  Please refer to  https://github.com/MihaiValentin/lunr-languages/issues/90

Because the current solution may not be plausible for everyone, so for the moment we may just leave the code as it is.

**Comment by jp7677** [comment]
Thanks for the feedback! Sorry to hear the issue with Chinese language, though that sounds indeed like of scope for this project.
