### ISSUE TITLE
CHORE: Reduce Docker image size

### ISSUE THREAD

**Issue by julrichkieffer** [avisi-cloud/structurizr-site-generatr#39]
The latest release (v1.0.10) downloaded as a Docker image is 484MB.  Given an Alpine Linux-based image with OpenJRE 8 is 85MB, we could **potentially cut the image size by up to 400MB**.

Not only would this make downloads and executions of the container more performant, but also reduce image build time and repository storage. Smaller images improves everyone's utility. Here's some reading for background and orientation:
- https://jpetazzo.github.io/2020/03/01/quest-minimal-docker-images-part-2/
- using `RUN apk add --no-cache` will prevent downloaded packages being included in the image

WBS of this chore:
- Dockerfile: base the image on [eclipse-temurin](https://hub.docker.com/_/eclipse-temurin/tags?page=1&name=alpine) (`18-jre-alpine` is 58MB) or [Jetty](https://hub.docker.com/_/jetty/tags?page=1&name=slim) (`9.4.48-jre8-slim-openjdk` is 78MB)
- Dockerfile: use `RUN apk add --no-cache` to avoid caching, and only include necessary packages
- Dockerfile: include only .jar or .war (compiled) packages, not source code

**Comment by dirkgroot** [comment]
Please be aware that the 58MB you're mentioning here is the **compressed size** of the image. Uncompressed, it is 168MB. So when comparing uncompressed sizes (as can be seen in the PR I created), the actual size difference is 171MB.

**Comment by dirkgroot** [comment]
> * Dockerfile: include only .jar or .war (compiled) packages, not source code

As far as I can see, the Docker image only includes binaries, and no source code.
