### ISSUE TITLE
Theme behaviour needs attention

### ISSUE THREAD

**Issue by julrichkieffer** [avisi-cloud/structurizr-site-generatr#40]
## Problem

This generator applies the same theme (it appears) regardless of the DSL default styles or `theme` / `themes` grammar.  Consequently, workspaces always generate the same look-and-feel to diagrams regardless of any settings in the .dsl file.

## Triage

To triage this behaviour, the following DSL is used: 

```structurizr
workspace "multi-relationships-summary" {

	model {
		cpq = softwareSystem "CPQ" "" "Web Browser"

		admin = person "Admin" {
			-> cpq "administers"
		}
		user = person "CPQ User" "" "Bank Staff" {
			-> cpq "uses"
		}
	}

	views {

		# theme default
		# themes default https://structurizr.com/share/36141/theme

		systemLandscape {
			autoLayout
			// show all static relationships and entities (see model)
			include *
		}

		dynamic * "CPQAdmin" {
			autoLayout
			title "CPQ Administration"

			// include static relationship; no change to relationship as only the parties are identified
			user -> cpq

			// replace static relationship; parties are identified but new relationships (both directions) are shown in this view only
			admin -> cpq "maintains products"
			admin -> cpq "maintains pricing"
			admin -> cpq "maintains promotions"
			admin -> cpq "maintains cross-selling"
			cpq -> admin "report abandonned carts"
			cpq -> admin "report sales overrides"
		}
	}
}
```

DSL / Workspace setting |  Expected | Actual | Notes
:------|:----:|:-----:|--------
_none_ | ![out-the-box expected](https://user-images.githubusercontent.com/895332/187917660-59bee3df-d129-421f-9394-7d8777af4a8f.png) | ![out-the-box actual](https://user-images.githubusercontent.com/895332/187918016-8d402700-954f-47c4-a31e-9474fd264b63.png) | While applying a theme when none is specified is welcome, a way to opt out of this is needed. By opting out, the Structurizr out-the-box theme (illustrated here) should be applied instead. |
`theme default` | ![default expected](https://user-images.githubusercontent.com/895332/187923022-4aacdbc5-f652-4eac-8f26-317a7b3b15ab.png) | ![default actual](https://user-images.githubusercontent.com/895332/187918016-8d402700-954f-47c4-a31e-9474fd264b63.png) | When a theme is specified, it should be applied.  Here the `default` value refers to the [Structurizr default theme](https://static.structurizr.com/themes/default/theme.json)  |
`themes default https://structurizr.com/share/36141/theme` | ![multiple expected](https://user-images.githubusercontent.com/895332/187925134-5fb661cc-1a75-44e5-8e85-f505be3e270a.png) | ![multiple actual](https://user-images.githubusercontent.com/895332/187918016-8d402700-954f-47c4-a31e-9474fd264b63.png) | When a theme is specified, it should be applied.  Here the `default` value refers to the [Structurizr default theme](https://static.structurizr.com/themes/default/theme.json). Subsequent themes are applied in order, like CSS. |

Expected results are taken from [Structurizr DSL Viewer](https://structurizr.com/dsl). Actual results are taken by running this generator against the same .dsl workspace, and retrieving the .png from the /build output.

**Comment by simonbrowndotje** [comment]
It looks like you're using the [C4PlantUMLExporter](https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/src/main/kotlin/nl/avisi/structurizr/site/generatr/site/DiagramGenerator.kt#L34), which uses it's own styling. Perhaps try the [StructurizrPlantUMLExporter](https://github.com/structurizr/export/blob/main/src/main/java/com/structurizr/export/plantuml/StructurizrPlantUMLExporter.java) or [MermaidDiagramExporter](https://github.com/structurizr/export/blob/main/src/main/java/com/structurizr/export/mermaid/MermaidDiagramExporter.java) instead.

You can also fork the [C4PlantUMLExporter](https://github.com/structurizr/export/blob/main/src/main/java/com/structurizr/export/plantuml/C4PlantUMLExporter.java) if needed.

**Comment by dirkgroot** [comment]
Hi @simonbrowndotje, thanks for your suggestion! I've tried using `StructurizrPlantUMLExporter` instead of `C4PlantUMLExporter`. However, `StructurizrPlantUMLExporter` doesn't seem to support themes. It does support `styles` (at least to some degree, I've tested it with Big Bank plc workspace, which includes some styles).

I prefer that this tool just uses the Structurizr libraries "out of the box", so I don't really mind if there are some limitations when it comes to available features.

So when it comes to supporting themes, I think the best solution would be to add support for `theme[s]` to `StructurizrPlantUMLExporter` and then add a command-line option to this tool, so the user can decide which diagram style they prefer: 

- PlantUML using the theme provided by the [C4-PlantUML](https://github.com/plantuml-stdlib/C4-PlantUML) library, but with no (or limited, I'm not sure) support for customization using `styles` or `theme`.
- PlantUML using `StructurizrPlantUMLExporter`, with support for `styles` and maybe also `theme[s]` in the future.

**Comment by simonbrowndotje** [comment]
Themes are supported, but you'll need to call the following method to load them into the workspace before running the export:

```
ThemeUtils.loadThemes(workspace);
```

**Comment by dirkgroot** [comment]
Awesome, that works, thanks!

Just double checking: As far as I can tell, support for themes/styles is very limited when using `C4PlantUMLEpxorter`. By looking at the source code, I only see that it supports customization of the shape of a `container`, to be either a cylinder or a pipe. Am I missing something?

**Comment by simonbrowndotje** [comment]
> support for themes/styles is very limited when using C4PlantUMLEpxorter

Correct ... C4-PlantUML was designed to use it's own styling, and while you can override this with tags, that's not supported by the `C4PlantUMLEpxorter`. I have no plans to add this functionality, but there's a fork that already does this -> https://github.com/cloudflightio/structurizr-export-c4plantuml

**Comment by dirkgroot** [comment]
Okay, thanks!

I think the best way to approach this, is to support (a subset of) the image formats supported by `export` command of the Structurizr CLI:

```shell
> structurizr-cli export
Missing required options: w, f
usage: export
 -f,--format <arg>      Export format: plantuml[/structurizr|c4plantuml]|websequencediagrams|mermaid|dot|ilograph|json|dsl|theme|fqcn
 -o,--output <arg>      Path to an output directory
 -w,--workspace <arg>   Path or URL to the workspace JSON file/DSL file(s)
```

A good start would be to support `plantuml/structurizr` and `plantuml/c4plantuml`.

**Comment by jp7677** [comment]
Related and from my experiences the actual "short-term" blocking issue for better customization: https://github.com/structurizr/export/issues/28

**Comment by jp7677** [comment]
Setting alternative colors and shapes seems to work just fine for me now when using tags i.c.w. with the latest version:

<details>
  <summary>Click to show DLS</summary>

```
views {
        properties {
            "c4plantuml.tags" "true"
        }

        ...

        styles {
            element "Person" {
                color #ffffff
                fontSize 22
                shape Person
            }
            element "Customer" {
                background #997662
            }
            element "Bank Staff" {
                background #137baa
            }
            element "Software System" {
                background #8ba65d
                color #ffffff
            }
            element "Existing System" {
                background #abb39d
                color #000000
            }
        ...
        }
...
}
```

</details>

Results in:


<details>
  <summary>Click to show Diagram</summary>

![Screenshot from 2023-01-17 10-08-01](https://user-images.githubusercontent.com/17219293/212855952-f63ac8df-4312-4b76-9fd2-40eff5fe2791.png)

</details>

(Please don't look to much at those random colors, I'm not a designer.. ;))

So at least from my side this is resolved. But not sure if i hit the same use case as the OP.

**Comment by dirkgroot** [comment]
Thanks @jp7677! I've created a PR #125 which makes sure that themes are loaded when loading a Structurizr DSL workspace. With this change, the output of the DSL from the OP looks like this, after setting the property `c4plantuml.tags` to `true`:

<details><summary>With no theme set</summary>

![image](https://user-images.githubusercontent.com/3872163/213123941-a8c6bdaa-55d2-47a4-8bc1-4e215bbf5700.png)

</details>

<details><summary>With <code>theme default</code></summary>

![image](https://user-images.githubusercontent.com/3872163/213124042-662ea70e-eec0-47f1-85c4-1f32528a0746.png)

</details>

<details><summary>With <code>themes default https://structurizr.com/share/36141/theme</code></summary>

![image](https://user-images.githubusercontent.com/3872163/213124228-1bfa4faf-eef2-4588-83b9-2679e2d11295.png)

</details>

<details><summary>With <code>themes https://structurizr.com/share/36141/theme</code></summary>

![image](https://user-images.githubusercontent.com/3872163/213124359-82a7bc39-b114-4757-8322-d92408a5f132.png)

</details>

I think this is very close to what @julrichkieffer expects, except for the case `themes default https://structurizr.com/share/36141/theme`.

@simonbrowndotje Could it be that `StructurizrPlantUMLExporter` handles multiple themes differently than `C4PlantUMLExporter`?

**Comment by simonbrowndotje** [comment]
> Could it be that StructurizrPlantUMLExporter handles multiple themes differently than C4PlantUMLExporter?

Yes, although the gap between how the two exporters handle styles has narrowed since this issue was opened:

 - https://github.com/structurizr/export/tree/main/src/main/java/com/structurizr/export/plantuml
 - https://github.com/structurizr/export/commit/70fa9473a1ed2d3ce50b390fe37bdd5ef2519aeb

**Comment by dirkgroot** [comment]
> Yes, although the gap between how the two exporters handle styles has narrowed since this issue was opened:

Okay, good to know, thanks!
