### ISSUE TITLE
FEATURE: Serve should re-generate website and refresh browser on changes

### ISSUE THREAD

**Issue by julrichkieffer** [avisi-cloud/structurizr-site-generatr#42]
## Problem

While the `serve` operation generates a website and loads a webserver to display it, any changes to source / input files does not reflect unless an entire new `serve` operation is executed. This makes the "inner loop" cumbersome, slow, and resource intensive.

## Reproduce

1.  Using the example workspace in this repository, execute the `serve` command against `workspace.dsl`:

    ```shell
    docker>  docker run -it --rm -p 8080:8080 -v C:/Projects/structurizr-site-generatr/docs/example:/var/model ghcr.io/avisi-cloud/structurizr-site-generatr:1.0.10 serve -w workspace.dsl

    Generating diagrams...
    SignIn...
    LiveDeployment...
    SystemContext...
    SystemLandscape...
    Containers...
    Components...
    DevelopmentDeployment...
    Generating site...
    Successfully generated diagrams and site

    Starting server...
    [main] INFO org.eclipse.jetty.server.Server - jetty-11.0.11; built: 2022-06-21T21:42:55.454Z; git: 58487315cb75e0f5c81cc6fa50096cbeb3b9554e; jvm 18.0.2+9
    [main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@49f5c307{/,null,AVAILABLE}
    [main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@305f7627{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
    [main] INFO org.eclipse.jetty.server.Server - Started Server@3d8bbcdc{STARTING}[11.0.11,sto=0] @53608ms
    Server started

    Open http://localhost:8080 in your browser to view the site
    ```

    Notice that several input files -- workspace, documentation, decisions, but not themes -- are all used to generate images and the web site. No errors are shown and the web site loads as expected.

1.  In a web browser, navigate to any diagram, decision or documentation page. Find the corresponding source file.

1.  Make a change to the source file and **save**. Notice that the web browser doesn't reflect the changed source file. Notice also that the web server **has not** noticed nor re-generated the images / web site.

## Expectation

To facilitate development, lower cognitive load, and improve architectural (user) productivity, input / source files should be monitored wherever possible. This should apply to any local files, but may exempt source files loaded via a url. When any monitored source / input file changes, both of the following should happen:

- The affected images or pages should be re-generated (i.e. a partial rebuild). OR re-generate all images and the whole site (i.e. full rebuild)
- All browser tabs open to the web site should refresh automatically (i.e. live reload)

**Comment by julrichkieffer** [comment]
Jetty is currently employed for the `serve` operation. However, I don't know whether it can meet the above expectations as it's designed for production use cases. 

Consider an alternative: deprecating Jetty in favour of Node for the `serve` operation. The image size would reduce greatly, and a made-for-dev lightweight dev server could be used instead.  Several options are available (not complete list):
- [server-reload](https://www.npmjs.com/package/server-reload)
- [live-server](https://www.npmjs.com/package/live-server)
- [local-web-server](https://www.npmjs.com/package/local-web-server)
- [node-dev-server](https://www.npmjs.com/package/@develon/node-dev-server)

**Comment by dirkgroot** [comment]
Currently, the development server monitors for file changes in the directory where the "main" workspace file is located, and all subdirectories. So as long as you don't reference files from other directories (using `!docs`, `!include`, `extends`, etc), every file which is part of the workspace will be monitored.

The only thing that's missing is auto refresh of the browser.

I'm a little bit hesitant about switching to Node, because I'd like to keep the technology stack for this tool as simple as possible.

Also, I'm not sure if switching to Node will reduce the image size. As far as I can tell, removing the Jetty dependency will reduce the image size by about 3 Mb max. Adding Node will add at least ±40 Mb to the image size (this is the size of the `bin` directory of the Node installation on my laptop). Am I missing something here?
