### ISSUE TITLE
System landscape diagram missing

### ISSUE THREAD

**Issue by Roymprog** [avisi-cloud/structurizr-site-generatr#426]
First of all, great work with this tool. It works very well, and am really happy with what you guys built.

When using the tool I noticed my system landscape diagram is not being created. Is this a bug or am I missing something? I do see it in the list after `Generating diagrams...` when I'm running the `serve` or the `generate-site` commands.
I would expect my system landscape diagram to show up under `Home` in the left hand menu.

**Comment by jp7677** [comment]
Thanks ;)

The system landscape diagram isn't automatically added to the side menu. You need to embed it in a markdown document and put it as second document into `workspace-docs` (the first in order is used as general site description).  See https://github.com/avisi-cloud/structurizr-site-generatr/tree/main/docs/example/workspace-docs and https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/docs/example/workspace-docs/01-embedding-diagrams-and-images.md#embedding-diagrams

**Comment by Roymprog** [comment]
Thanks, that's what I was looking for!
