### ISSUE TITLE
FEATURE: Bundle ADR Tools and expose as `adr` operation

### ISSUE THREAD

**Issue by julrichkieffer** [avisi-cloud/structurizr-site-generatr#43]
## Problem

Particularly relevent for the Docker distro, although a web site can be generated from a .dsl, any input architecture decisions must either be hand-written and managed, or relies on architect to have [ADR Tools](https://github.com/npryce/adr-tools) installed on the host machine. This latter approach departs from the Docker ethos of "everything needed is in the container".

## Suggested solution

As [ADR Tools](https://github.com/npryce/adr-tools) is merely a set of shell scripts, there's no new dependencies to manage.  Depending on how the `ENTRYPOINT` vs `CMD` suggestion from #31 is handled, these scripts could either:
- CMD: be installed and called directly via the host `docker run` command
- ENTRYPOINT: be exposed via a new `adr` operation of this project, which delegates to the installed ADR Tools scripts.  This approach will bring consistency between both installed and Docker approaches, but require development & maintenance of this pass-through operation

Via either way, Docker distro users will be able to manage ADRs *and* generate websites via the same Docker image.

The only complication to address is that [ADR Tools](https://github.com/npryce/adr-tools) relies on an `EDITOR` environment variable to load a text editor / IDE. This assumes the script and editor are executing on the same host, which under this suggested approach, is false. However, owing to WSL2, it **is** possible for the Docker container's shell to start an **independant** process on the host. For example:

```shell
container> pwd
/var/model

container> code .

```

Presumably `code` will be stored in the `EDITOR` variable. And by WSL2 "magic" the host starts VS Code with the container's `pwd` open in context.  That is, any changes will appear to persist into the container, which in turn via the `-v [host path]:/var/model` mounting will realise as a change to the architect's source / input files.

**Comment by dirkgroot** [comment]
I'm closing this issue. As stated in the README (since today), the intended use for the Docker image is for usage in CI pipelines. Using it for development is possible, but not an actively supported use case.
