### ISSUE TITLE
Provide an example

### ISSUE THREAD

**Issue by Riduidel** [avisi-cloud/structurizr-site-generatr#5]
Can youc reate an example repository with the website generated in github pages ?

**Comment by thojkooi** [comment]
Hi @Riduidel, we will look into creating an example for that. :+1:

**Comment by dirkgroot** [comment]
Hi @Riduidel, I've set up this repository to publish an example website on https://avisi-cloud.github.io/structurizr-site-generatr.

Thanks for your suggestion!
