### ISSUE TITLE
search is broken on Windows

### ISSUE THREAD

**Issue by zhelyan** [avisi-cloud/structurizr-site-generatr#506]
Small issue - searching from a component view is broken as relative paths [use](https://github.com/avisi-cloud/structurizr-site-generatr/blob/1a5203e38df8a89b087421a7cd4e255859547c3f/src/main/kotlin/nl/avisi/structurizr/site/generatr/site/RelativeUrl.kt#L8)  the windows file separator `\` -  i.e the relative path is not a http path

**Comment by dirkgroot** [comment]
Hi @zhelyan, thanks for reporting!

I've made a potential fix for this issue, but unfortunately, I don't have easy access to a Windows computer to test this. Could you try if this fixes your issue?

You can download the binaries containing this fix using the following URL: https://github.com/avisi-cloud/structurizr-site-generatr/actions/runs/9170553411/artifacts/1521911067

**Comment by dirkgroot** [comment]
I'm going to merge this MR.

**Comment by zhelyan** [comment]
@dirkgroot sorry for the late reply

It is still broken unfortunately.  I think the issue is that the method constructs file paths using platform dependant separators. They need to be normalized to http compliant paths. Perhaps the simplest thing to do would be e.g

```kotlin
URI(relativeTo + "/" + this).normalize().toURL().toString()
```

**Comment by jp7677** [comment]
Another attempt for this issue https://github.com/avisi-cloud/structurizr-site-generatr/pull/557

**Comment by jp7677** [comment]
@zhelyan I've merged the PR since this change is a good idea anyway. Feel free to reopen if this issue still
