### ISSUE TITLE
Internal Links from markdown pages are missing trailing slashes on generated HTML pages 

### ISSUE THREAD

**Issue by UBessle** [avisi-cloud/structurizr-site-generatr#530]
If i place a link on a markdown page to some other internal page, generated by structurizr-site-generatr, the generated link is missing the trailing slash. 

This does not cause problems with the included development server, which redirects `/master/decisions/1` automatically to the correct page URL `/master/decisions/1/index.html`

But this automatic redirection is a non standard behavior, that not every Web Server supports out of the box. We use nginx for serving our productive architecture documentation site and there such links missing the trailing slash will fail.

That was the reason, why standard links generated from structurizr-site-generatr were changed some time ago to have trailing slashes. Unfortunately that is not true for links on markdown pages. For markdown pages the opposite is true, trainling slashes will be automatically removed.

You can easily reproduce the cumbersome behavior for links when you extend docs/example/workspace-docs/00-index.md with the following text lines at the end

```
Placing links on markdown pages is easy. You can link to:

* an overview page like [Workspace decisions](/decisions/),
* an individual decision [ADR-0001. record architecture decisions](/decisions/1/)
* or some system documentation like [Internet Banking](/internet-banking-system/).
```

If you look onto the generated links, you will find that the generated HTML links are pointing to relative URL's without the trailing slash.

```
<ul>
 <li>an overview page like <a href="decisions">Workspace decisions</a>,</li>
 <li>an individual decision <a href="decisions/1">ADR-0001. record architecture decisions</a></li>
 <li>or some system documentation like <a href="internet-banking-system">Internet Banking</a>.</li>
</ul>
```

The only workaround currently usable is to use the full relative URL's in markdown documentation pages

```
Placing links on markdown pages is easy. You can link to:

* an overview page like [Workspace decisions](/decisions/index.html),
* an individual decision [ADR-0001. record architecture decisions](/decisions/1/index.html)
* or some system documentation like [Internet Banking](/internet-banking-system/index.html).
```

The other workaround is to use special redirection rules in nginx configuration like

```
rewrite ^([^.]*[^/])$ $1/ permanent;
```

That would rewrite all URL's without a trailing slash to a URL with a trailing slash, but only if the URL does not contain a dot, because we do not want to rewrite CSS or JS file URL's. Problems start to arise, if the URL contains dots somewhere in the base path or some system name. And IMHO it's not worth to go into the discussion with other people to convince them, to introduce such rules into their standard and battle proven nginx configuration because some tool is generating incorrect URL's.

So i would appreciate it, if you could apply the same logic for links in markdown files, that you already apply to links in the left menu and on the overview pages for decisions, systems and so on.

Thanks a lot
Uwe

**Comment by jp7677** [comment]
Hi @UBessle, thanks for the well made issue report. Does https://github.com/avisi-cloud/structurizr-site-generatr/pull/534 fixes all your scenarios?
